# Deployment do Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "news"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
        - name: kubenews
          image: pedrorjung/projetogerencia:v1
          env:
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_DATABASE
              value: "news"
            - name: DB_HOST
              value: "postgre"
---
apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer
