name: CI-CD

on:
  push:
    branches: [main]

jobs:
  CI: 
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4.1.7
    - name: Construção da imagem Docker
      uses: docker/build-push-action@v6.5.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          preisj/projetogerencia:v1
          preisj/projetogerencia:latest
          


